mvc:
  payments:
    index:
      create:
        allow: user
      complete:
        allow: guest
      canceled:
        allow: guest
    paypal:
      allow: guest
    management:
      allow: admin
